=== Black-Sphere-Studios/planeshader/media/feather.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="featherGUI" xmlns="featherGUI" >

  <xs:simpleType name="fgFlagsAny">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]+(|[A-Z]+)*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fgFlags">
    <xs:restriction base="xs:string">
      <xs:pattern value="(BACKGROUND|NOCLIP|IGNORE|HIDDEN|EXPANDX|EXPANDY|EXPAND|SNAPX|SNAPY|SNAP)(\|(BACKGROUND|NOCLIP|IGNORE|HIDDEN|EXPANDX|EXPANDY|EXPAND|SNAPX|SNAPY|SNAP))*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fgFlagsText">
    <xs:restriction base="xs:string">
      <xs:pattern value="(BACKGROUND|NOCLIP|IGNORE|HIDDEN|EXPANDX|EXPANDY|EXPAND|SNAPX|SNAPY|SNAP|CHARWRAP|WORDWRAP|ELLIPSES|RTL|RIGHTALIGN|CENTER|SUBPIXEL)(\|(BACKGROUND|NOCLIP|IGNORE|HIDDEN|EXPANDX|EXPANDY|EXPAND|SNAPX|SNAPY|SNAP|CHARWRAP|WORDWRAP|ELLIPSES|RTL|RIGHTALIGN|CENTER|SUBPIXEL))*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fgFlagsCombobox">
    <xs:restriction base="xs:string">
      <xs:pattern value="(BACKGROUND|NOCLIP|IGNORE|HIDDEN|EXPANDX|EXPANDY|EXPAND|SNAPX|SNAPY|SNAP|HIDEH|HIDEV|SHOWH|SHOWV|EDITBOX)(\|(BACKGROUND|NOCLIP|IGNORE|HIDDEN|EXPANDX|EXPANDY|EXPAND|SNAPX|SNAPY|SNAP|HIDEH|HIDEV|SHOWH|SHOWV|EDITBOX))*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fgFlagsButton">
    <xs:restriction base="xs:string">
      <xs:pattern value="(BACKGROUND|NOCLIP|IGNORE|HIDDEN|EXPANDX|EXPANDY|EXPAND|SNAPX|SNAPY|SNAP|NOFOCUS)(\|(BACKGROUND|NOCLIP|IGNORE|HIDDEN|EXPANDX|EXPANDY|EXPAND|SNAPX|SNAPY|SNAP|NOFOCUS))*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fgFlagsScrollbar">
    <xs:restriction base="xs:string">
      <xs:pattern value="(BACKGROUND|NOCLIP|IGNORE|HIDDEN|EXPANDX|EXPANDY|EXPAND|SNAPX|SNAPY|SNAP|HIDEH|HIDEV|SHOWH|SHOWV)(\|(BACKGROUND|NOCLIP|IGNORE|HIDDEN|EXPANDX|EXPANDY|EXPAND|SNAPX|SNAPY|SNAP|HIDEH|HIDEV|SHOWH|SHOWV))*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fgFlagsList">
    <xs:restriction base="xs:string">
      <xs:pattern value="(BACKGROUND|NOCLIP|IGNORE|HIDDEN|EXPANDX|EXPANDY|EXPAND|SNAPX|SNAPY|SNAP|HIDEH|HIDEV|SHOWH|SHOWV|TILEX|TILEY|TILE|DISTRIBUTEX|DISTRIBUTEY|DISTRIBUTE|FIXEDSIZE|SINGLESELECT|MULTISELECT|DRAGGABLE)(\|(BACKGROUND|NOCLIP|IGNORE|HIDDEN|EXPANDX|EXPANDY|EXPAND|SNAPX|SNAPY|SNAP|HIDEH|HIDEV|SHOWH|SHOWV|TILEX|TILEY|TILE|DISTRIBUTEX|DISTRIBUTEY|DISTRIBUTE|FIXEDSIZE|SINGLESELECT|MULTISELECT|DRAGGABLE))*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fgFlagsResource">
    <xs:restriction base="xs:string">
      <xs:pattern value="(BACKGROUND|NOCLIP|IGNORE|HIDDEN|EXPANDX|EXPANDY|EXPAND|SNAPX|SNAPY|SNAP|ROUNDRECT|CIRCLE|LINE)(\|(BACKGROUND|NOCLIP|IGNORE|HIDDEN|EXPANDX|EXPANDY|EXPAND|SNAPX|SNAPY|SNAP|ROUNDRECT|CIRCLE|LINE))*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fgFlagsBox">
    <xs:restriction base="xs:string">
      <xs:pattern value="(BACKGROUND|NOCLIP|IGNORE|HIDDEN|EXPANDX|EXPANDY|EXPAND|SNAPX|SNAPY|SNAP|HIDEH|HIDEV|SHOWH|SHOWV|TILEX|TILEY|TILE|DISTRIBUTEX|DISTRIBUTEY|DISTRIBUTE|FIXEDSIZE)(\|(BACKGROUND|NOCLIP|IGNORE|HIDDEN|EXPANDX|EXPANDY|EXPAND|SNAPX|SNAPY|SNAP|HIDEH|HIDEV|SHOWH|SHOWV|TILEX|TILEY|TILE|DISTRIBUTEX|DISTRIBUTEY|DISTRIBUTE|FIXEDSIZE))*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fgFlagsWindow">
    <xs:restriction base="xs:string">
      <xs:pattern value="(BACKGROUND|NOCLIP|IGNORE|HIDDEN|EXPANDX|EXPANDY|EXPAND|SNAPX|SNAPY|SNAP|MINIMIZABLE|MAXIMIZABLE|RESIZABLE|NOTITLEBAR|NOBORDER)(\|(BACKGROUND|NOCLIP|IGNORE|HIDDEN|EXPANDX|EXPANDY|EXPAND|SNAPX|SNAPY|SNAP|MINIMIZABLE|MAXIMIZABLE|RESIZABLE|NOTITLEBAR|NOBORDER))*" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fgCheckboxState">
    <xs:restriction base="xs:string">
      <xs:enumeration value="none"/>
      <xs:enumeration value="checked"/>
      <xs:enumeration value="indeterminate"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fgFont">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^;]*;[0-9]*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fgHex">
    <xs:restriction base="xs:string">
      <xs:pattern value="0x[0-9A-Fa-f]+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fgCoord">
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9]+(\.[0-9]+)?)?(em)?:([0-9]+(\.[0-9]+)?)?"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Rect">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]+(\.[0-9]+)?(em)?, ?[0-9]+(\.[0-9]+)?(em)?, ?[0-9]+(\.[0-9]+)?(em)?, ?[0-9]+(\.[0-9]+)?(em)?"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fgRect">
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9]+(\.[0-9]+)?)?(em)?:([0-9]+(\.[0-9]+)?)?, ?([0-9]+(\.[0-9]+)?)?(em)?:([0-9]+(\.[0-9]+)?)?, ?([0-9]+(\.[0-9]+)?)?(em)?:([0-9]+(\.[0-9]+)?)?, ?([0-9]+(\.[0-9]+)?)?(em)?:([0-9]+(\.[0-9]+)?)?"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="fgVec">
    <xs:restriction base="xs:string">
      <xs:pattern value="([0-9]+(\.[0-9]+)?)?(em)?:([0-9]+(\.[0-9]+)?)?, ?([0-9]+(\.[0-9]+)?)?(em)?:([0-9]+(\.[0-9]+)?)?"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:group name="fgControlGroup">
    <xs:choice>
      <xs:element name="Element" type="fgElement" />
      <xs:element name="Control" type="fgControl" />
      <xs:element name="Box" type="fgBox"  />
      <xs:element name="Scrollbar" type="fgScrollbar" />
      <xs:element name="Button" type="fgButton"/>
      <xs:element name="Checkbox" type="fgCheckbox" />
      <xs:element name="Combobox" type="fgCombobox" />
      <xs:element name="Dropdown" type="fgDropdown" />
      <xs:element name="List" type="fgList" />
      <xs:element name="Menu" type="fgMenu"  />
      <xs:element name="Progressbar" type="fgProgressbar"  />
      <xs:element name="RadioButton" type="fgRadioButton" />
      <xs:element name="Resource" type="fgResource" />
      <xs:element name="Slider" type="fgSlider" />
      <xs:element name="TabGroup" type="fgTabGroup" />
      <xs:element name="Text" type="fgText" />
      <xs:element name="Textbox" type="fgTextbox" />
      <xs:element name="Window" type="fgWindow" />
      <xs:element name="TreeView" type="fgTreeView" />
      <xs:element name="Toolbar" type="fgToolbar" />
    </xs:choice>
  </xs:group>

  <xs:complexType name="fgLayoutBase">
    <!-- id is the UNIQUE layout identifier string -->
    <xs:attribute name="id" type="xs:string"/>
    <!-- this is the name used for styles. names do NOT have to be unique -->
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="order" type="xs:integer"/>
    <xs:attribute name="area" type="fgRect"/>
    <xs:attribute name="center" type="fgVec"/>
    <xs:attribute name="rotation" type="xs:decimal"/>
    <xs:attribute name="left" type="fgCoord"/>
    <xs:attribute name="top" type="fgCoord"/>
    <xs:attribute name="right" type="fgCoord"/>
    <xs:attribute name="bottom" type="fgCoord"/>
    <xs:attribute name="width" type="fgCoord"/>
    <xs:attribute name="height" type="fgCoord"/>
    <xs:attribute name="skin" type="xs:string"/>
    <xs:attribute name="alpha" type="xs:decimal"/>
    <!--<xs:attribute name="transform" type="fgTransform"/>-->
    <xs:attribute name="margin" type="Rect"/>
    <xs:attribute name="padding" type="Rect"/>
  </xs:complexType>

  <xs:complexType name="fgLayout">
    <xs:complexContent>
      <xs:extension base="fgLayoutBase">
        <xs:sequence>
          <xs:group ref="fgControlGroup" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgElement">
    <xs:complexContent>
      <xs:extension base="fgLayout">
        <xs:attribute name="flags" type="fgFlags"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgControl">
    <xs:complexContent>
      <xs:extension base="fgLayout">
        <xs:attribute name="flags" type="fgFlags"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgButton">
    <xs:complexContent>
      <xs:extension base="fgLayout">
        <xs:attribute name="flags" type="fgFlagsButton"/>
        <xs:attribute name="text" type="xs:string"/>
        <xs:attribute name="color" type="fgHex"/>
        <xs:attribute name="font" type="fgFont"/>
        <xs:attribute name="lineheight" type="xs:decimal"/>
        <xs:attribute name="letterspacing" type="xs:decimal"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgBox">
    <xs:complexContent>
      <xs:extension base="fgLayout">
        <xs:attribute name="flags" type="fgFlagsBox"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgScrollbar">
    <xs:complexContent>
      <xs:extension base="fgLayout">
        <xs:attribute name="flags" type="fgFlagsScrollbar"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgCheckbox">
    <xs:complexContent>
      <xs:extension base="fgLayout">
        <xs:attribute name="flags" type="fgFlags"/>
        <xs:attribute name="state" type="fgCheckboxState" default="none"/>
        <xs:attribute name="text" type="xs:string"/>
        <xs:attribute name="color" type="fgHex"/>
        <xs:attribute name="font" type="fgFont"/>
        <xs:attribute name="lineheight" type="xs:decimal"/>
        <xs:attribute name="letterspacing" type="xs:decimal"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgCombobox">
    <xs:complexContent>
      <xs:extension base="fgLayout">
        <xs:attribute name="flags" type="fgFlagsCombobox"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgDropdown">
    <xs:complexContent>
      <xs:extension base="fgLayout">
        <xs:attribute name="flags" type="fgFlagsList"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgList">
    <xs:complexContent>
      <xs:extension base="fgLayout">
        <xs:attribute name="flags" type="fgFlagsList"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgMenu">
    <xs:complexContent>
      <xs:extension base="fgLayoutBase">
        <xs:choice>
          <xs:element name="MenuItem" type="fgElement" minOccurs="0" maxOccurs="unbounded" />
        </xs:choice>
        <xs:attribute name="flags" type="fgFlagsScrollbar"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgProgressbar">
    <xs:complexContent>
      <xs:extension base="fgLayout">
        <xs:attribute name="flags" type="fgFlags"/>
        <xs:attribute name="state" type="xs:decimal" default="0.0"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgRadioButton">
    <xs:complexContent>
      <xs:extension base="fgLayout">
        <xs:attribute name="flags" type="fgFlags"/>
        <xs:attribute name="state" type="xs:boolean" default="false"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgResource">
    <xs:complexContent>
      <xs:extension base="fgLayout">
        <xs:attribute name="flags" type="fgFlagsResource"/>
        <xs:attribute name="color" type="fgHex"/>
        <xs:attribute name="uv" type="fgRect"/>
        <xs:attribute name="resource" type="xs:string"/>
        <xs:attribute name="edgecolor" type="fgHex"/>
        <xs:attribute name="outline" type="xs:decimal"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgSlider">
    <xs:complexContent>
      <xs:extension base="fgLayout">
        <xs:attribute name="flags" type="fgFlags"/>
        <xs:attribute name="state" type="xs:decimal" default="0.0"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgTabGroup">
    <xs:complexContent>
      <xs:extension base="fgLayoutBase">
        <xs:choice>
          <xs:element name="Tab" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
              <xs:complexContent>
                <xs:extension base="fgScrollbar">
                  <xs:attribute name="text" type="xs:string"/>
                </xs:extension>
              </xs:complexContent>
            </xs:complexType>
          </xs:element>
        </xs:choice>
        <xs:attribute name="flags" type="fgFlags"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgText">
    <xs:complexContent>
      <xs:extension base="fgLayout">
        <xs:attribute name="flags" type="fgFlagsText"/>
        <xs:attribute name="text" type="xs:string"/>
        <xs:attribute name="color" type="fgHex"/>
        <xs:attribute name="font" type="fgFont"/>
        <xs:attribute name="lineheight" type="xs:decimal"/>
        <xs:attribute name="letterspacing" type="xs:decimal"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgTextbox">
    <xs:complexContent>
      <xs:extension base="fgLayout">
        <xs:attribute name="flags" type="fgFlagsScrollbar"/>
        <xs:attribute name="text" type="xs:string"/>
        <xs:attribute name="placeholder" type="xs:string"/>
        <xs:attribute name="color" type="fgHex"/>
        <xs:attribute name="font" type="fgFont"/>
        <xs:attribute name="lineheight" type="xs:decimal"/>
        <xs:attribute name="letterspacing" type="xs:decimal"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgWindow">
    <xs:complexContent>
      <xs:extension base="fgLayout">
        <xs:attribute name="flags" type="fgFlagsWindow"/>
        <xs:attribute name="text" type="xs:string"/>
        <xs:attribute name="color" type="fgHex"/>
        <xs:attribute name="font" type="fgFont"/>
        <xs:attribute name="lineheight" type="xs:decimal"/>
        <xs:attribute name="letterspacing" type="xs:decimal"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgTreeItem">
    <xs:complexContent>
      <xs:extension base="fgLayoutBase">
        <xs:sequence>
          <xs:group ref="fgControlGroup" minOccurs="0" maxOccurs="unbounded" />
          <xs:element name="TreeItem" type="fgTreeItem" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgTreeView">
    <xs:complexContent>
      <xs:extension base="fgLayoutBase">
        <xs:choice>
          <xs:element name="TreeItem" type="fgTreeItem" minOccurs="0" maxOccurs="unbounded" />
        </xs:choice>
        <xs:attribute name="flags" type="fgFlagsScrollbar"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="fgToolbar">
    <xs:complexContent>
      <xs:extension base="fgLayoutBase">
        <xs:choice>
          <xs:element name="ToolGroup" minOccurs="0" maxOccurs="unbounded">
            <xs:complexType>
              <xs:complexContent>
                <xs:extension base="fgLayout">
                  <xs:attribute name="flags" type="fgFlags"/>
                </xs:extension>
              </xs:complexContent>
            </xs:complexType>
          </xs:element>
        </xs:choice>
        <xs:attribute name="flags" type="fgFlags"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:element name="Layout">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="fgLayout">
          <xs:attribute name="flags" type="fgFlags"/>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
    
  <xs:complexType name="fgStyle">
    <xs:complexContent>
      <xs:extension base="fgLayoutBase">
        <xs:attribute name="flags" type="fgFlagsAny"/>
        <xs:attribute name="text" type="xs:string"/>
        <xs:attribute name="color" type="fgHex"/>
        <xs:attribute name="font" type="fgFont"/>
        <xs:attribute name="lineheight" type="xs:decimal"/>
        <xs:attribute name="letterspacing" type="xs:decimal"/>
        <xs:attribute name="state" type="xs:string"/>
        <xs:attribute name="uv" type="fgRect"/>
        <xs:attribute name="resource" type="xs:string"/>
        <xs:attribute name="edgecolor" type="fgHex"/>
        <xs:attribute name="outline" type="xs:decimal"/>
        <xs:attribute name="placeholder" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:group name="fgSkinGroup">
    <xs:choice>
      <xs:element name="Element" type="fgElement" />
      <xs:element name="Control" type="fgControl" />
      <xs:element name="Box" type="fgBox"  />
      <xs:element name="Scrollbar" type="fgScrollbar" />
      <xs:element name="Button" type="fgButton"/>
      <xs:element name="Checkbox" type="fgCheckbox" />
      <xs:element name="Combobox" type="fgCombobox" />
      <xs:element name="Dropdown" type="fgDropdown" />
      <xs:element name="List" type="fgList" />
      <xs:element name="Menu" type="fgMenu"  />
      <xs:element name="Progressbar" type="fgProgressbar"  />
      <xs:element name="RadioButton" type="fgRadioButton" />
      <xs:element name="Resource" type="fgResource" />
      <xs:element name="Slider" type="fgSlider" />
      <xs:element name="TabGroup" type="fgTabGroup" />
      <xs:element name="Text" type="fgText" />
      <xs:element name="Textbox" type="fgTextbox" />
      <xs:element name="Window" type="fgWindow" />
      <xs:element name="TreeView" type="fgTreeView" />
      <xs:element name="Style" type="fgStyle" />
      <xs:element name="Skin" type="fgSkin" />
    </xs:choice>
  </xs:group>

  <xs:complexType name="fgSkin">
    <xs:complexContent>
      <xs:extension base="fgStyle">
        <xs:sequence>
          <xs:group ref="fgSkinGroup" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="inherit" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:element name="Skin" type="fgSkin" />

</xs:schema>

=== Black-Sphere-Studios/planeshader/media/feathertest.xml
<?xml version="1.0" encoding="UTF-8"?>
<fg:Layout xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:fg="featherGUI" xsi:schemaLocation="featherGUI feather.xsd">
  <Button name="buttontest" flags="EXPAND">
    <Resource resource="../media/circle.png" color="0xFFFFFFFF" flags="EXPAND|IGNORE" />
  </Button>
  <Window area="130 100 510 420" text="test window" color="0xFFFFFFFF" font="arial;14" padding="10,22,10,10">
    <TabControl area="0 0 100% 100%">
      <Tab text="Tab 1">
        <Button area="10, 10, 0, 0" flags="EXPAND" text="Not Pressed" onaction="makepressed" />
        <Box area="10, 160, 150, 240" flags="TILEY|EXPANDX" max-width="100">
          <Checkbox text="Check test 1" flags="EXPAND" />
          <Checkbox text="Check test 22" flags="EXPAND" />
          <Checkbox text="Check test 3" flags="EXPAND" />
          <Checkbox text="Check test 4" flags="EXPAND" />
          <Checkbox text="Check test 5" flags="EXPAND" />
        </Box>
        <RadioButton area="190, 130, 0, 0" text="Radio Test 1" flags="EXPAND" />
        <RadioButton area="190, 160, 0, 0" text="Radio Test 2" flags="EXPAND" />
        <RadioButton area="190, 190, 0, 0" text="Radio Test 3" flags="EXPAND" />
        <Slider area="10, 70, 150, 90" value="0" range="500" onvalue="statelistener" />
        <Progressbar value="0.0" area="10, 100, 150, 125" />
      </Tab>
      <Tab text="Long Name Tab">
        <Textbox area="140, 30, 210, 150" flags="WORDWRAP" placeholder="placeholder" />
        <Dropdown area="10, 200, 150, 230" flags="TILEY" max-height="60">
          <Text area="0, 0, 100%, 20" text="Drop 1" />
          <Text area="0, 0, 100%, 20" text="Drop 2" />
          <Text flags="EXPAND" text="Drop 3" />
          <Text area="0, 0, 100%, 20" text="Drop 4" />
        </Dropdown>
        <List>
          <ListItem area="0, 0, 100%, 20" />
          <Text area="0, 0, 100%, 20" text="List 1" />
          <Text area="0, 0, 100%, 20" text="List 2" />
          <Text area="0, 0, 100%, 20" text="List 3" />
          <Text area="0, 0, 100%, 20" text="List 4" />
          <ListItem area="0, 0, 100%, 20" />
          <Text area="0, 0, 100%, 20" text="List 5" />
        </List>
      </Tab>
      <Tab text="Tab 3"></Tab>
      <Tab text="Tab 4"></Tab>
    </TabControl>
    <Menu right="100%" flags="EXPANDY|TILEX">
      <MenuItem text="File">
        <Menu area="100% 0 100% 0" flags="EXPAND|TILEY|HIDDEN">
          <MenuItem text="New" />
          <MenuItem text="Open" />
          <MenuItem text="Save" />
          <MenuItem text="Save As..." />
          <MenuItem />
          <MenuItem text="Quit" />
        </Menu>
      </MenuItem>
      <MenuItem text="Edit">
        <Menu area="100% 0 100% 0" flags="EXPAND|TILEY|HIDDEN">
          <MenuItem text="Cut" />
          <MenuItem text="Copy" />
          <MenuItem text="Paste" />
          <MenuItem />
          <MenuItem text="Transform" >
            <Menu area="100% 0 100% 0" flags="EXPAND|TILEY|HIDDEN">
              <MenuItem text="Free Transform" >
                <Menu area="100% 0 100% 0" flags="EXPAND|TILEY|HIDDEN">
                  <MenuItem text="Apply" />
                </Menu>
              </MenuItem>
              <MenuItem />
              <MenuItem text="Rotate" />
              <MenuItem text="Skew" />
              <MenuItem text="Resize" />
            </Menu>
          </MenuItem>
        </Menu>
      </MenuItem>
      <MenuItem text="Options" />
      <MenuItem text="Help">
        <Menu area="100% 0 100% 0" flags="EXPAND|TILEY|HIDDEN">
          <MenuItem text="About" />
        </Menu>
      </MenuItem>
    </Menu>
  </Window>  
</fg:Layout>
